# Sample YAML file to deploy Data Factory resources from an ARM template
name: CD

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true

      - name: Export ARM Template
        id: export
        uses: Azure/data-factory-export-action@v1.0.1
        # with:
        #   path: <data-factory-dir> # replace by the folder that contains the Data Factory resources and the package.json
      
      - name: Deploy resources
        uses: Azure/data-factory-deploy-action@v1.0.0
        with:
          resourceGroupName: rg-adf-github-demo
          dataFactoryName: adfghdemo
          armTemplateFile: '${{steps.export.outputs.arm-template-directory}}/ARMTemplateForFactory.json'
          armTemplateParametersFile: '${{steps.export.outputs.arm-template-directory}}/ARMTemplateParametersForFactory.json'
          # additionalParameters: 'key1=value key2=value keyN=value' [optional]

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: data-factory-package
          path: ${{ steps.export.outputs.arm-template-directory }}
          if-no-files-found: error
