# Sample YAML file to validate and export an ARM template into a build artifact
# Requires a package.json file located in the target repository

name: CI

on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Validate
        uses: Azure/data-factory-validate-action@v1.1.0
        # with:
        #   path: <data-factory-dir> # replace by the folder that contains the Data Factory resources and the package.json

      # Generate the ARM template into the destination folder, which is the same as selecting "Publish" from the UX.
      # The ARM template generated isn't published to the live version of the factory.
      - name: Export ARM Template
        id: export
        uses: Azure/data-factory-export-action@v1.0.0
        # with:
        #   path: <data-factory-dir> # replace by the folder that contains the Data Factory resources and the package.json

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: data-factory-package
          path: ${{ steps.export.outputs.arm-template-directory }}
          if-no-files-found: error
